[2024-06-09T03:08:36.725+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T03:08:36.735+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:08:32.317722+00:00 [queued]>
[2024-06-09T03:08:36.739+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:08:32.317722+00:00 [queued]>
[2024-06-09T03:08:36.739+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T03:08:36.744+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): visualize_data> on 2024-06-09 03:08:32.317722+00:00
[2024-06-09T03:08:36.748+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=684) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T03:08:36.749+0000] {standard_task_runner.py:63} INFO - Started process 694 to run task
[2024-06-09T03:08:36.750+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'visualize_data', 'manual__2024-06-09T03:08:32.317722+00:00', '--job-id', '57', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmp8w9xgnnw']
[2024-06-09T03:08:36.751+0000] {standard_task_runner.py:91} INFO - Job 57: Subtask visualize_data
[2024-06-09T03:08:36.772+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:08:32.317722+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T03:08:36.817+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='visualize_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T03:08:32.317722+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T03:08:32.317722+00:00'
[2024-06-09T03:08:36.818+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T03:08:36.897+0000] {logging_mixin.py:188} INFO -                 Open      High       Low     Close  Adj Close     Volume
2002-05-23  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
2002-05-24  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2002-05-28  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
2002-05-29  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
2002-05-30  1.107857  1.107857  1.071429  1.071429   1.071429   10154200
[2024-06-09T03:08:36.897+0000] {finsight_pipeline_functions.py:44} INFO - Converting 'Date' column to datetime format and setting it as index.
[2024-06-09T03:08:36.898+0000] {finsight_pipeline_functions.py:95} ERROR - Failed to visualize or upload data: "None of ['Date'] are in the columns"
[2024-06-09T03:08:36.898+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T03:08:36.898+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 46, in visualize_raw_data
    df.set_index('Date', inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5870, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['Date'] are in the columns"
[2024-06-09T03:08:36.904+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=visualize_data, run_id=manual__2024-06-09T03:08:32.317722+00:00, execution_date=20240609T030832, start_date=20240609T030836, end_date=20240609T030836
[2024-06-09T03:08:36.910+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 57 for task visualize_data ("None of ['Date'] are in the columns"; 694)
[2024-06-09T03:08:36.931+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T03:08:36.944+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T03:08:36.947+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
