[2024-06-09T03:14:27.277+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T03:14:27.300+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:14:22.083352+00:00 [queued]>
[2024-06-09T03:14:27.307+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:14:22.083352+00:00 [queued]>
[2024-06-09T03:14:27.308+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T03:14:27.322+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): visualize_data> on 2024-06-09 03:14:22.083352+00:00
[2024-06-09T03:14:27.329+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=807) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T03:14:27.330+0000] {standard_task_runner.py:63} INFO - Started process 817 to run task
[2024-06-09T03:14:27.333+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'visualize_data', 'manual__2024-06-09T03:14:22.083352+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmpvpxdoywz']
[2024-06-09T03:14:27.337+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask visualize_data
[2024-06-09T03:14:27.373+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:14:22.083352+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T03:14:27.441+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='visualize_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T03:14:22.083352+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T03:14:22.083352+00:00'
[2024-06-09T03:14:27.445+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T03:14:27.475+0000] {logging_mixin.py:188} INFO -        Open      High       Low     Close  Adj Close     Volume
0  1.156429  1.242857  1.145714  1.196429   1.196429  104790000
1  1.214286  1.225000  1.197143  1.210000   1.210000   11104800
2  1.213571  1.232143  1.157143  1.157143   1.157143    6609400
3  1.164286  1.164286  1.085714  1.103571   1.103571    6757800
4  1.107857  1.107857  1.071429  1.071429   1.071429   10154200
[2024-06-09T03:14:27.475+0000] {finsight_pipeline_functions.py:45} INFO - Converting 'Date' column to datetime format and setting it as index.
[2024-06-09T03:14:27.476+0000] {finsight_pipeline_functions.py:96} ERROR - Failed to visualize or upload data: 'Date'
[2024-06-09T03:14:27.476+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T03:14:27.476+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3791, in get_loc
    return self._engine.get_loc(casted_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "index.pyx", line 152, in pandas._libs.index.IndexEngine.get_loc
  File "index.pyx", line 181, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'Date'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 46, in visualize_raw_data
    df['Date'] = pd.to_datetime(df['Date'])
                                ~~^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3893, in __getitem__
    indexer = self.columns.get_loc(key)
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/indexes/base.py", line 3798, in get_loc
    raise KeyError(key) from err
KeyError: 'Date'
[2024-06-09T03:14:27.485+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=visualize_data, run_id=manual__2024-06-09T03:14:22.083352+00:00, execution_date=20240609T031422, start_date=20240609T031427, end_date=20240609T031427
[2024-06-09T03:14:27.490+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task visualize_data ('Date'; 817)
[2024-06-09T03:14:27.513+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T03:14:27.536+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T03:14:27.542+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
