[2024-06-09T03:06:55.491+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T03:06:55.503+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:06:51.237076+00:00 [queued]>
[2024-06-09T03:06:55.508+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:06:51.237076+00:00 [queued]>
[2024-06-09T03:06:55.508+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T03:06:55.515+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): visualize_data> on 2024-06-09 03:06:51.237076+00:00
[2024-06-09T03:06:55.520+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=640) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T03:06:55.521+0000] {standard_task_runner.py:63} INFO - Started process 650 to run task
[2024-06-09T03:06:55.522+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'visualize_data', 'manual__2024-06-09T03:06:51.237076+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmpx8z0o881']
[2024-06-09T03:06:55.524+0000] {standard_task_runner.py:91} INFO - Job 55: Subtask visualize_data
[2024-06-09T03:06:55.562+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T03:06:51.237076+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T03:06:55.613+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='visualize_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T03:06:51.237076+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T03:06:51.237076+00:00'
[2024-06-09T03:06:55.614+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T03:06:55.699+0000] {finsight_pipeline_functions.py:43} INFO - Converting 'Date' column to datetime format and setting it as index.
[2024-06-09T03:06:55.700+0000] {finsight_pipeline_functions.py:94} ERROR - Failed to visualize or upload data: "None of ['Date'] are in the columns"
[2024-06-09T03:06:55.700+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T03:06:55.700+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 45, in visualize_raw_data
    df.set_index('Date', inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5870, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['Date'] are in the columns"
[2024-06-09T03:06:55.708+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=visualize_data, run_id=manual__2024-06-09T03:06:51.237076+00:00, execution_date=20240609T030651, start_date=20240609T030655, end_date=20240609T030655
[2024-06-09T03:06:55.714+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 55 for task visualize_data ("None of ['Date'] are in the columns"; 650)
[2024-06-09T03:06:55.747+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T03:06:55.763+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T03:06:55.765+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
