[2024-06-09T02:48:18.943+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-09T02:48:18.953+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T02:48:15.313921+00:00 [queued]>
[2024-06-09T02:48:18.957+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T02:48:15.313921+00:00 [queued]>
[2024-06-09T02:48:18.957+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-09T02:48:18.962+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): visualize_data> on 2024-06-09 02:48:15.313921+00:00
[2024-06-09T02:48:18.972+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=287) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-09T02:48:18.973+0000] {standard_task_runner.py:63} INFO - Started process 297 to run task
[2024-06-09T02:48:18.974+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'FinSight_pipeline', 'visualize_data', 'manual__2024-06-09T02:48:15.313921+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/FinSight/finsight_pipeline_taks.py', '--cfg-path', '/tmp/tmprcpb16ru']
[2024-06-09T02:48:18.976+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask visualize_data
[2024-06-09T02:48:19.000+0000] {task_command.py:426} INFO - Running <TaskInstance: FinSight_pipeline.visualize_data manual__2024-06-09T02:48:15.313921+00:00 [running]> on host bc9e3c56deeb
[2024-06-09T02:48:19.052+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Group 2' AIRFLOW_CTX_DAG_ID='FinSight_pipeline' AIRFLOW_CTX_TASK_ID='visualize_data' AIRFLOW_CTX_EXECUTION_DATE='2024-06-09T02:48:15.313921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-09T02:48:15.313921+00:00'
[2024-06-09T02:48:19.053+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-09T02:48:19.062+0000] {finsight_pipeline_functions.py:37} INFO - Reading data from                   Open        High  ...   Adj Close     Volume
Date                                ...                       
2002-05-23    1.156429    1.242857  ...    1.196429  104790000
2002-05-24    1.214286    1.225000  ...    1.210000   11104800
2002-05-28    1.213571    1.232143  ...    1.157143    6609400
2002-05-29    1.164286    1.164286  ...    1.103571    6757800
2002-05-30    1.107857    1.107857  ...    1.071429   10154200
...                ...         ...  ...         ...        ...
2022-12-23  296.179993  298.459991  ...  294.959991    4251100
2022-12-27  293.190002  293.570007  ...  284.170013    5778100
2022-12-28  281.920013  285.190002  ...  276.880005    5964400
2022-12-29  283.179993  295.500000  ...  291.119995    9588500
2022-12-30  285.529999  295.010010  ...  294.880005    7566900

[5189 rows x 6 columns]
[2024-06-09T02:48:19.062+0000] {finsight_pipeline_functions.py:43} INFO - Converting 'Date' column to datetime format and setting it as index.
[2024-06-09T02:48:19.062+0000] {finsight_pipeline_functions.py:94} ERROR - Failed to visualize or upload data: "None of ['Date'] are in the columns"
[2024-06-09T02:48:19.062+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-09T02:48:19.063+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/FinSight/finsight_pipeline_functions.py", line 45, in visualize_raw_data
    df.set_index('Date', inplace=True)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 5870, in set_index
    raise KeyError(f"None of {missing} are in the columns")
KeyError: "None of ['Date'] are in the columns"
[2024-06-09T02:48:19.069+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=FinSight_pipeline, task_id=visualize_data, run_id=manual__2024-06-09T02:48:15.313921+00:00, execution_date=20240609T024815, start_date=20240609T024818, end_date=20240609T024819
[2024-06-09T02:48:19.075+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 46 for task visualize_data ("None of ['Date'] are in the columns"; 297)
[2024-06-09T02:48:19.118+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-06-09T02:48:19.133+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-09T02:48:19.135+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
